# Generated by Django 4.2.4 on 2023-08-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_employee_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
