# Generated by Django 4.2.4 on 2023-08-28 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_employee_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(default='abv@abv.bg', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
