# Generated by Django 4.2.4 on 2023-08-28 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_nullblankdemo'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_full_time',
            field=models.BooleanField(null=True),
        ),
    ]
